services:
  db:
    container_name: mysql-todo-list-app
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
      DATABASE_HOST: db
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - generic-list-crud-volume:/var/lib/mysql

volumes:
  generic-list-crud-volume: